export const chatSuggestions = [
    "Does your name hold any special significance?",
    "How was your childhood?",
    "What's your relationhip with your parents?",
    "What is your greatest strength?",
    "What is your greatest weakness?",
    "Have you ever been in love?",
    "What is your greatest fear?",
    "What are your hobbies?",
    "Who is your greatest rival?",
    "Who is your greatest ally",
    "What sets you apart from other people?",
    "What would you do for a living if you were not an adventurer?",
    "Do you have any scars? What are their stories?",
    "Do you have any tattoos? What are their stories?",
    "If you were an animal, what animal would you be?",
    "If you could change anything about yourself, what would that be?",
    "What is your favorite color?",
    "What is your favorite food?",
    "What is your biggest secret?",
    "What is your greatest achievement?",
    "Where do you see yourself in the future?",
    "What is your favorite weapon?",
];
